name: Prepare TinyLlama
description: Download TinyLlama and launch it
runs:
  using: "composite"
  steps:
    - name: Download TinyLlama model
      shell: bash
      run: curl -OL https://huggingface.co/TheBloke/TinyLlama-1.1B-1T-OpenOrca-GGUF/resolve/main/tinyllama-1.1b-1t-openorca.Q3_K_M.gguf

    - name: Setup binfmt with APE
      shell: bash
      run: |
        sudo wget -O /usr/bin/ape https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf
        sudo chmod +x /usr/bin/ape
        sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
        sudo sh -c "echo ':APE-jart:M::jartsr::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

    - name: Run TinyLlama with Llamafile
      shell: bash
      run: |
        curl -OL https://github.com/Mozilla-Ocho/llamafile/releases/download/0.6.2/llamafile-0.6.2.zip
        unzip llamafile-0.6.2.zip
        ./llamafile-0.6.2/bin/llamafile -m ./tinyllama-1.1b-1t-openorca.Q3_K_M.gguf &
