name: Prepare Phi 2
description: Download Phi 2 and launch it
runs:
  using: "composite"
  steps:
    - name: Download Phi 2 model
      shell: bash
      run: curl -OL https://huggingface.co/TheBloke/dolphin-2_6-phi-2-GGUF/resolve/main/dolphin-2_6-phi-2.Q3_K_M.gguf

    - name: Setup binfmt with APE
      shell: bash
      run: |
        sudo wget -O /usr/bin/ape https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf
        sudo chmod +x /usr/bin/ape
        sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
        sudo sh -c "echo ':APE-jart:M::jartsr::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

    - name: Run Phi 2 with Llamafile
      shell: bash
      run: |
        curl -OL https://github.com/Mozilla-Ocho/llamafile/releases/download/0.6.2/llamafile-0.6.2.zip
        unzip llamafile-0.6.2.zip
        ./llamafile-0.6.2/bin/llamafile -m ./dolphin-2_6-phi-2.Q3_K_M.gguf &
